spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
server:
  port: 8082
management:
  endpoint:
    health:
      probes:
        enabled: true
---
logging:
  level:
    fabianopinto.threebunkers: debug
---
#spring:
#  r2dbc:
#    url: r2dbc:postgresql://localhost:54320/postgres
#    username: Mwq4UxjWVtwXidri
#    password: nU6YjjwdP6XsIKK4
